## Temel Çalışma Soruları

NumPy'de sıralama, çarpma işleminin toplama işleminden önce yapılmasını sağlar.

**map()**, kısa ve öz bir şekilde sadece bir fonksiyon uygulamak istediğinizde idealdir. Örneğin: map(str.capitalize, kelimeler).
**Liste** Anlaması, daha karmaşık işlemler veya kolay okunabilirlik için daha uygundur. Örneğin: [kelime.capitalize() for kelime in kelimeler].

## Pandas ile Eksik Değer Tespiti ve Doldurma
Pandas, eksik değerleri tespit etmek ve doldurmak için çok güçlü araçlar sağlar:

### Eksik Değer Tespiti:
- **isnull():** Eksik değerleri (NaN) True olarak işaretler.
- **notnull():** Eksik olmayan değerleri True olarak işaretler.
Eksik Değerleri Ortalama ile Doldurma:
- **fillna():** Eksik değerleri belirtilen bir yöntem veya değerle doldurur.

- **.empty**, DataFrame'in tamamen boş olup olmadığını kontrol eder
- Eğer bir DataFrame içindeki boş değerleri (NaN, None gibi) kontrol etmek istiyorsanız, **pd.isnull()** veya **.isna()** fonksiyonlarını kullanabilirsiniz:

In [60]:
import pandas as pd

# Örnek veri
data = {
    "Ad": ["Ali", "Ayşe", "Ahmet"],
    "Yaş": [25, None, 28],
    "Maaş": [3000, 4000, None]
}
df = pd.DataFrame(data)

# Eksik değerleri tespit etme
print(df.isnull())

# Her sütunun ortalamasıyla eksik değerleri doldurma
df["Yaş"] = df["Yaş"].fillna(df["Yaş"].mean())
df["Maaş"] = df["Maaş"].fillna(df["Maaş"].mean())

print("\nEksik değerler doldurulduktan sonra:\n", df)


      Ad    Yaş   Maaş
0  False  False  False
1  False   True  False
2  False  False   True

Eksik değerler doldurulduktan sonra:
       Ad   Yaş    Maaş
0    Ali  25.0  3000.0
1   Ayşe  26.5  4000.0
2  Ahmet  28.0  3500.0


## NumPy ile Eksik Değer Tespiti ve Doldurma
NumPy, eksik değerleri **np.nan** ile ifade eder ve işlemler için temel fonksiyonlar sağlar.

### Eksik Değer Tespiti:
- np.isnan(): Bir dizide eksik değerlerin yerlerini bulur.
### Eksik Değerleri Ortalama ile Doldurma:
- NumPy'nın fonksiyonları (np.nanmean) eksik değerleri hesaba katmadan işlem yapabilir.

In [61]:
import numpy as np

# NumPy dizisi
data = np.array([[25, 3000], [np.nan, 4000], [28, np.nan]])

# Eksik değerleri tespit etme
print("Eksik Değerler:\n", np.isnan(data))

# Sütun ortalamalarını hesaplama (NaN'ları dikkate almaz)
col_means = np.nanmean(data, axis=0)

# Eksik değerleri sütun ortalamalarıyla doldurma
filled_data = np.where(np.isnan(data), col_means, data)

print("\nDoldurulmuş Veri:\n", filled_data)


Eksik Değerler:
 [[False False]
 [ True False]
 [False  True]]

Doldurulmuş Veri:
 [[  25.  3000. ]
 [  26.5 4000. ]
 [  28.  3500. ]]


**axis=0**: Sütunlar üzerinde işlem yapmak için

**axis=1**: Satırlar üzerinde işlem yapmak için

.mean() .sum()  .max() .min()

- Pandas'ta **sort_values()** fonksiyonu bir DataFrame veya Series'in **değerlerini** sıralamak için kullanılır. Bu fonksiyon, belirtilen bir sütuna göre verileri artan ya da azalan şekilde sıralayabilir.
- **sort_index()**: İndekslere göre sıralama yapar.

In [63]:
import pandas as pd

# Örnek veri
data = {
    "Ad": ["Ali", "Ayşe", "Ahmet"],
    "Yaş": [25, 30, 28],
    "Maaş": [3000, 4000, 3500]
}
df = pd.DataFrame(data)

# "Yaş" sütununa göre sıralama
siralama = df.sort_values("Yaş")
print(siralama)

# "Maaş" sütununa göre azalan sıralama
siralama = df.sort_values("Maaş", ascending=False)
print(siralama)

# Önce "Yaş", sonra "Maaş" sütununa göre sıralama
siralama = df.sort_values(["Yaş", "Maaş"], ascending=[True, False])
print(siralama)

# Series örneği
ser = pd.Series([3000, 4000, 3500], index=["Ali", "Ayşe", "Ahmet"])

# Değerlere göre sıralama
siralama = ser.sort_values()
print(siralama)




      Ad  Yaş  Maaş
0    Ali   25  3000
2  Ahmet   28  3500
1   Ayşe   30  4000
      Ad  Yaş  Maaş
1   Ayşe   30  4000
2  Ahmet   28  3500
0    Ali   25  3000
      Ad  Yaş  Maaş
0    Ali   25  3000
2  Ahmet   28  3500
1   Ayşe   30  4000
Ali      3000
Ahmet    3500
Ayşe     4000
dtype: int64


In [3]:
numbers = [3,7,5,8,2]
total = sum(numbers)
total

25

In [8]:
print(f"toplam: {total}")

toplam: 25


In [9]:
import pandas as pd
data = {
    "Ad": ["Ayşe","Ali","Ece"],
    "Yaş":[28,40,50],
    "Maaş":[30000,40000,50000]
}
df = pd.DataFrame(data)

In [15]:
df.mean(numeric_only=True)

Yaş        39.333333
Maaş    40000.000000
dtype: float64

In [17]:
import numpy as np

A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
C = A + B
C

array([[ 6,  8],
       [10, 12]])

#### Soru 1: Python Veri Tipleri

In [18]:
x = [1, 2, 3]
y = (1, 2, 3)
z = {1, 2, 3}
print(type(x), type(y), type(z))

<class 'list'> <class 'tuple'> <class 'set'>


Python'da döngü değişkeni (i) için başlangıç değeri atamak zorunlu değildir, çünkü Python bunu iterable üzerinden otomatik olarak atar. Ancak C++ gibi dillerde bu tür değer atamalarını açıkça yapmak gerekir. Bu fark, Python'un dinamik ve yüksek seviyeli bir dil olmasından kaynaklanır.

#### Soru 2: Döngüler

In [19]:
for i in range(3):
    print(i, end=" ")


0 1 2 

#### Soru 3: List Comprehension

In [21]:
numbers = [x**2 for x in range(5) if x % 2 == 0]
print(numbers)


[0, 4, 16]


#### Soru 4: Pandas ile Veri Manipülasyonu

In [23]:
import pandas as pd
data = {'A': [10, 20], 'B': [30, 40]}
df = pd.DataFrame(data)
print(df.loc[0, 'B'])


30


#### Soru 5: NumPy ile Matris İşlemleri

In [24]:
import numpy as np
arr = np.array([[1, 2], [3, 4]])
print(arr[1, 0])


3


#### Soru 6: Python Fonksiyonları

In [30]:
def multiply(a, b=5):
    return a * b

result = multiply(3)
print(result)


15


#### Soru 7: Hata Yönetimi

In [31]:
try: 
    x= 1/0
except ZeroDivisionError:
    print("Hata: Sifira bolme hatasi")

Hata: Sifira bolme hatasi


#### Soru 8: Değişken Türü

Python'da bir string (x) ile bir tam sayı (y) çarpılırsa, string sayı kadar tekrarlanır. Bu durumda, "5" stringi 3 defa tekrarlanır.

In [32]:
x = "5"
y = 3
z = x * y
print(z)


555


#### Soru 9: Lambda Fonksiyonu

In [34]:
f = lambda x: x * 2
print(f(5))


10


**map()** fonksiyonu, verilen lambda fonksiyonunu numbers listesindeki her elemana uygular

In [35]:
numbers = [1, 2, 3, 4]
result = list(map(lambda x: x**2 if x % 2 == 0 else x**3, numbers))
print(result)


[1, 4, 27, 16]


#### Soru 10: Pandas ile Veri Seçimi

In [36]:
import pandas as pd
data = {"A": [1, 2], "B": [3, 4]}
df = pd.DataFrame(data)
print(df["A"][1])


2


#### Soru 11: NumPy ile Diziler

In [37]:
import numpy as np
arr = np.array([1, 2, 3, 4])
print(arr + 10)


[11 12 13 14]


In [44]:
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
result = arr1 * arr2 + 10
print(result)


[14 20 28]


In [45]:
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
result = 10 + arr1 * arr2
print(result)


[14 20 28]


**.where()**

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
result = np.where(arr % 2 == 0, arr * 2, arr * 3)
print(result)


**arr[1:3, 0:2]:**
    2. ve 3. satırlar arasını seçer (1:3).
    0. ve 1. sütunları seçer (0:2).

In [46]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr[1:3, 0:2])


[[4 5]
 [7 8]]


In [47]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
result = np.max(arr, axis=0)  # Maksimumları sütun bazında al
print(result)


[7 8 9]


### Filtreleme

In [48]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
result = arr[arr % 2 == 0]
print(result)


[2 4]


In [49]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
arr[-1] = 10
print(arr)


[ 1  2  3  4 10]


In [50]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])
result = arr + 10
print(result)


[[11 12 13]
 [14 15 16]]


#### Soru 12: String İşlemleri

In [39]:
s = "python"
print(s[::-1])


nohtyp


#### Soru 13: Python Sözlükleri

In [41]:
d = {"a": 1, "b": 2, "c": 3}
print(d.get("d", "Bulunamadı"))


Bulunamadı


#### Soru 10: Zaman Modülü

In [43]:
import time
print(time.strftime("%Y"))


2024


### Python
#### Soru 1: Python'da Kapalı Fonksiyonlar

In [51]:
def outer_function(x):
    def inner_function(y):
        return x + y
    return inner_function

func = outer_function(10)
print(func(5))


15


outer_function iç fonksiyon inner_function'u döndürür.
func = outer_function(10) ile inner_function 10 ile çağrılacak şekilde ayarlanır.
func(5) iç fonksiyon çağrıldığında x parametresi 10 ve y parametresi 5 alır.
Sonuç: 10 + 5 = 15

#### Soru 2: Varsayılan Parametreler

In [52]:
def greet(name, greeting="Hello"):
    return f"{greeting}, {name}!"

print(greet("Alice"))
print(greet("Bob", "Hi"))


Hello, Alice!
Hi, Bob!


#### Soru 3: Geçici Değişkenler (Nonlocal)

nonlocal anahtar kelimesi, iç fonksiyonun dış fonksiyonun değişkenlerine erişmesine ve onları değiştirmesine olanak tanır.
func() çağrıldığında x değeri 10'dan 11'e yükseltilir.
Sonuç: 11.

In [53]:
def outer():
    x = 10
    def inner():
        nonlocal x
        x += 1
        return x
    return inner

func = outer()
print(func())


11
