# Numpy Array'i Oluşturmak

In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4,5])

In [3]:
type(a)

numpy.ndarray

In [8]:
np.array([3.14,4,2,13],dtype = "int")

array([ 3,  4,  2, 13])

### sifirdan array oluşturmak

In [13]:
np.zeros(10, dtype="int")

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [15]:
np.ones((2,5), dtype="int")

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [16]:
np.full((2,5),3)

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [20]:
np.arange(0,41,4)

array([ 0,  4,  8, 12, 16, 20, 24, 28, 32, 36, 40])

In [25]:
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

### (ortalama, standart sapma, matris boyutu)

In [28]:
np.random.normal(10,5,(2,5))

array([[12.82069727, 11.84846916, 13.00609688, 13.65018141,  6.01805716],
       [ 8.38922003, 11.47141204, 10.42154596, 14.03907968, 13.03042237]])

### 0 ile 10 arası random

In [29]:
np.random.randint(0,10,(2,5))

array([[0, 4, 4, 6, 2],
       [9, 1, 2, 4, 1]])