# Yeniden Şekillendirme (reshaping)

In [4]:
import numpy as np

In [5]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.arange(1,10).reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
a = np.arange(1,10)

In [9]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
a.ndim

1

In [12]:
a.reshape((1,9))

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [14]:
a.reshape((1,9)).ndim

2