# Array Sıralama (Sorting)

In [1]:
import numpy as np

In [2]:
v = np.array([2,1,4,3,5])

In [3]:
v

array([2, 1, 4, 3, 5])

In [4]:
np.sort(v)

array([1, 2, 3, 4, 5])

### iki boyutlu array sıralama

In [6]:
m = np.random.normal(20,5,(3,3))

In [7]:
m

array([[25.24808429, 22.98331065, 19.3086797 ],
       [16.81922849, 20.43754253, 20.90944205],
       [24.25768042, 19.05148279, 21.05686982]])

In [8]:
np.sort(m,axis =1)

array([[19.3086797 , 22.98331065, 25.24808429],
       [16.81922849, 20.43754253, 20.90944205],
       [19.05148279, 21.05686982, 24.25768042]])

In [9]:
np.sort(m,axis=0)

array([[16.81922849, 19.05148279, 19.3086797 ],
       [24.25768042, 20.43754253, 20.90944205],
       [25.24808429, 22.98331065, 21.05686982]])