# Array Ayırma(Splitting)

In [1]:
import numpy as np

In [2]:
x = [1,2,3,99,99,99,3,2,1]

In [ ]:
# 3 ' e kadar böl,5'e kadar böl--- 0'dan başlar

In [3]:
np.split(x,[3,5])

[array([1, 2, 3]), array([99, 99]), array([99,  3,  2,  1])]

In [ ]:
# ayrılan arrayleri isimlendirme

In [ ]:
a,b,c = np.split(x,[3,5])

### iki boyutlu ayırma

In [4]:
m = np.arange(16).reshape(4,4)
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
# 2.indexe kadar böl 0,1,2.

In [5]:
np.vsplit(m,[2])

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [6]:
ust, alt = np.vsplit(m,[2])

In [7]:
ust

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [8]:
alt

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [9]:
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [10]:
np.hsplit(m,[2])

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [11]:
sag, sol = np.hsplit(m,[2])

In [12]:
sag

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [13]:
sol

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])