# Neden Numpy

In [3]:
a=[1,2,3,4]
b=[2,3,4,5]
a

[1, 2, 3, 4]

In [4]:
b

[2, 3, 4, 5]

In [6]:
ab = []
for i in range(0,len(a)):
    ab.append(a[i]*b[i])
ab

[2, 6, 12, 20]

In [6]:
import numpy as np

In [7]:
a = np.array([1,2,3,4])
b = np.array([2,3,4,5])


array([ 2,  6, 12, 20])

In [8]:
a * b

array([ 2,  6, 12, 20])

In [17]:
python_list=[1,2,3,4]

In [16]:
numpy_list = np.array(python_list)

In [18]:
numpy_list

array([1, 2, 3, 4])